### ISSUE TITLE
Container tasks

### ISSUE THREAD

**Issue by Fastidious** [key-networks/ztncui-containerized#2]
How do I make the container autostart after a reboot? How can I make it, so configuration (including password) persists after a reboot? Thanks!

**Comment by key-networks** [comment]
The configuration should persist because of the --volume options in the docker command.

To start the container automatically on reboot:
1. Enable docker with:
`sudo systemctl enable docker`

2.  Add the --restart option to the docker command:
`docker run --restart unless-stopped --net="host" --name ztncui --volume ztncui:/opt/key-networks/ztncui/etc/ --volume zt1:/var/lib/zerotier-one/ --cap-add=NET_ADMIN keynetworks/ztncui`

3. Remove HTTPS_PORT=3443 from the .env file:
`docker exec -it ztncui /bin/bash`
`cat /dev/null > /opt/key-networks/ztncui/.env`
`exit`

4. Reboot the system and test access on http://localhost:3000

Let me know if this does what you need.

**Comment by Fastidious** [comment]
It did what I needed, though I ended up just installing `zerotier-one`, and `ztncui` separately, directly on my server. It works like a charm. Thanks for it!
